"""funciones de ia: juez, defensa, cv y proyecto congelado

Revision ID: c1137f034fee
Revises: 8111d774fcdd
Create Date: 2026-09-28 18:18:37.855448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c1137f034fee'
down_revision: Union[str, Sequence[str], None] = '8111d774fcdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defensa',
    sa.Column('entrega_id', sa.Uuid(), nullable=False),
    sa.Column('estado', sa.String(length=16), nullable=False),
    sa.Column('modelo', sa.String(length=120), nullable=False),
    sa.Column('momento_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('momento_respuesta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preguntas', sa.Text(), nullable=False),
    sa.Column('rubrica_privada', sa.Text(), nullable=False),
    sa.Column('respuestas', sa.Text(), nullable=True),
    sa.Column('calificaciones', sa.Text(), nullable=True),
    sa.Column('puntaje', sa.Integer(), nullable=True),
    sa.Column('aprobada', sa.Boolean(), nullable=True),
    sa.Column('retroalimentacion', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['entrega_id'], ['entrega.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('defensa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_defensa_entrega_id'), ['entrega_id'], unique=False)

    op.create_table('revision_ia',
    sa.Column('evaluacion_id', sa.Uuid(), nullable=False),
    sa.Column('estado', sa.String(length=16), nullable=False),
    sa.Column('modelo', sa.String(length=120), nullable=False),
    sa.Column('version_instrucciones', sa.String(length=40), nullable=False),
    sa.Column('momento', sa.DateTime(timezone=True), nullable=False),
    sa.Column('huella_proyecto', sa.String(length=64), nullable=True),
    sa.Column('puntaje_global', sa.Integer(), nullable=True),
    sa.Column('dimensiones', sa.Text(), nullable=False),
    sa.Column('aptitudes', sa.Text(), nullable=False),
    sa.Column('fortalezas', sa.Text(), nullable=False),
    sa.Column('mejoras', sa.Text(), nullable=False),
    sa.Column('analisis_estatico', sa.Text(), nullable=False),
    sa.Column('resumen', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['evaluacion_id'], ['evaluacion.id'], ),
    sa.PrimaryKeyConstraint('evaluacion_id')
    )
    with op.batch_alter_table('entrega', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proyecto', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('huella_proyecto', sa.String(length=64), nullable=True))

    with op.batch_alter_table('perfil_estudiante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resumen_ia', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('momento_resumen', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('reto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dificultad', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('aptitudes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('proyecto_base', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reto', schema=None) as batch_op:
        batch_op.drop_column('proyecto_base')
        batch_op.drop_column('aptitudes')
        batch_op.drop_column('dificultad')

    with op.batch_alter_table('perfil_estudiante', schema=None) as batch_op:
        batch_op.drop_column('momento_resumen')
        batch_op.drop_column('resumen_ia')

    with op.batch_alter_table('entrega', schema=None) as batch_op:
        batch_op.drop_column('huella_proyecto')
        batch_op.drop_column('proyecto')

    op.drop_table('revision_ia')
    with op.batch_alter_table('defensa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_defensa_entrega_id'))

    op.drop_table('defensa')
    # ### end Alembic commands ###
